[package]
name = "raytrace"
version = "0.1.0"
authors = ["darkruby"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.1"
rayon = "1.1.0"